apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
  namespace: todos
spec:
  replicas: 1 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: mysql # Label to match with the selector in the Service
  template:
    metadata:
      labels:
        app: mysql # Label for the Pod template
    spec:
      containers:
      - name: mysql
        image: mysql
        ports:
        - containerPort: 3306 # The port MySQL listens on
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        - name: MYSQL_ROOT_HOST
          value: "%"
        - name: MYSQL_DATABASE
          value: devops_p1
      
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: todos
spec:
  selector:
    app: mysql # Selects the Pods with label app=mysql
  ports:
    - protocol: TCP
      port: 3306 # The port exposed by the service
      targetPort: 3306 # The port that MySQL listens on