apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-server
  labels:
    app: todos-server
  namespace: todos
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: todos-server # Label to match with the selector in the Service
  template:
    metadata:
      labels:
        app: todos-server # Label for the Pod template
    spec:
      containers:
      - name: todos-server
        image: markeybass/todos-server:latest
        ports:
        - containerPort: 5000 # The port your server application listens on
        env:
        - name: MYSQL_HOST
          value: mysql-service
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PORT
          value: '3306'
        - name: MYSQL_PASSWORD
          value: '123456'
        - name: MYSQL_DB
          value: devops_p1
---
apiVersion: v1
kind: Service
metadata:
  name: todos-server-service
  namespace: todos
spec:
  type: LoadBalancer
  selector:
    app: todos-server # Selects the Pods with label app=todos-server
  ports:
    - protocol: TCP
      port: 80 # The port exposed by the service
      targetPort: 5000 # The port that the container listens on
      nodePort: 30002